pinata:
  uri: https://api.pinata.cloud/pinning/pinJSONToIPFS
  apiKey: 3171d7f3aa6de68d1df2
  secretApiKey: 2f14ebc83172fbde3d8e16145a43b995fb6eb871a55d94058a1ded5575670fa8
server:
  port: 8080
  authSecret: "123456789a"
log:
  zap:
    level: info
    encoding: json
    disableCaller: true
    disableStacktrace: false
    outputPaths: ["stderr", "stdout"]
    errorOutputPaths: ["stderr"]
  stderrRedirectFile: error.log  
subLogs:
  handler:
    zap:
      development: true
      level: debug
      encoding: json
      disableStacktrace: true
      outputPaths: ["stderr", "stdout"]
      errorOutputPaths: ["stderr"]
    stderrRedirectFile: error.log
    stdLogRedirect: true
storage:
  provider: s3
s3:
  endpoint: http://localhost:9001
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  region: "aa"
